script: "bin/rake --trace 2>&1"
bundler_args: "--binstubs --without development"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
env:
  - RAILS_VERSION=3.1.1
  - RAILS_VERSION=3.1.0
  - RAILS_VERSION=3.0.10
  - RAILS_VERSION=3-1-stable
  - RAILS_VERSION=3-0-stable
  - RAILS_VERSION=master
