script: "gemfiles/bin/rake --trace 2>&1"
bundler_args: "--binstubs --without development"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
gemfile:
  - gemfiles/rails-3.0.10
  - gemfiles/rails-3.1.0
  - gemfiles/rails-3.1.1
  - gemfiles/rails-3-1-stable
  - gemfiles/rails-master
