script: "bin/rake --trace 2>&1"
bundler_args: "--binstubs --without documentation"
before_install: gem install bundler --pre
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
env:
  - RAILS_VERSION=3.2.12
  - RAILS_VERSION=3.1.11
  - RAILS_VERSION=3.0.20
  - RAILS_VERSION=3-2-stable
  - RAILS_VERSION=3-1-stable
  - RAILS_VERSION=3-0-stable
  - RAILS_VERSION=master
matrix:
  exclude:
    - rvm: 1.8.7
      env: RAILS_VERSION=master
    - rvm: 1.9.2
      env: RAILS_VERSION=master
    - rvm: 2.0.0
      env: RAILS_VERSION=3.1.11
    - rvm: 2.0.0
      env: RAILS_VERSION=3.0.20
    - rvm: 2.0.0
      env: RAILS_VERSION=3-2-stable
    - rvm: 2.0.0
      env: RAILS_VERSION=3-1-stable
    - rvm: 2.0.0
      env: RAILS_VERSION=3-0-stable
  allow_failures:
    - rvm: 1.9.3
      env: RAILS_VERSION=master
    - env: RAILS_VERSION=3-2-stable
    - env: RAILS_VERSION=3-1-stable
    - env: RAILS_VERSION=3-0-stable
    - rvm: 2.0.0
